esphome:
  name: office
  platform: ESP32
  board: nodemcu-32s

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
api:
  password: !secret api_password
 
ota:
  password: !secret ota_password

external_components:
  # Using a fork for components/ support, original: https://github.com/j5lien/esphome-idasen-desk-controller
  - source: github://bahlo/esphome-idasen-desk-controller@add-components-folder

idasen_desk_controller:
    mac_address: !secret idasen_desk_mac_address
    bluetooth_callback: false

cover:
  - platform: idasen_desk_controller
    name: "Desk"

sensor:
  - platform: idasen_desk_controller
    desk_height:
      name: "Desk Height (cm)"
      accuracy_decimals: 1 # mm precision

binary_sensor:
  - platform: idasen_desk_controller
    name: "Desk Connection"
    type: CONNECTION
  - platform: idasen_desk_controller
    name: "Desk Moving"
    type: MOVING
